### ISSUE TITLE
Denoify

### ISSUE THREAD

**Issue by garronej** [oscarotero/nodedeno#1]
I might still your idea of gathering all dependencies in a single `deps.ts` in [denoify](https://github.com/garronej/denoify). It is very neat,  I hope you don't mind.  
If you are interested I can let you push the commit so the feature is attributed to you?

**Comment by oscarotero** [comment]
Hey, thanks for telling me!
Don't worry about the attribution, I'm happy to "inspire" to other projects 😄

**Comment by garronej** [comment]
Thanks for your work. You rocks
